const HOST = "http://localhost:9999/";

const METHOD_TYPE = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE"
}

const ERROR = {
    ACCOUNT_IS_LOCKED_BY_ADMIN: "ACCOUNT_IS_LOCKED_BY_ADMIN",
    ACCOUNT_IS_LOCKED: "ACCOUNT_IS_LOCKED",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    BAD_CREDITIAL: "BAD_CREDITIAL",
    BAD_REQUEST: "BAD_REQUEST",
    NOT_FOUND_EMAIL: "NOT_FOUND_EMAIL",
    EMAIL_IS_INVALID: "EMAIL_IS_INVALID",
    NEW_PASSWORD_SAME_CURRENT_PASSWORD: "NEW_PASSWORD_SAME_CURRENT_PASSWORD",
    CURRENT_PASSWORD_NOT_MATCH: "CURRENT_PASSWORD_NOT_MATCH",
    ERROR_UPDATE_PASSWORD: "ERROR_UPDATE_PASSWORD"
}

const WARNING_TYPE = {
    NGUONG_AP_CAO: 101,
    NGUONG_AP_THAP: 102,
    NHIET_DO_TIEP_XUC: 103,
    COS_THAP_TONG: 104,
    QUA_TAI: 105,
    TAN_SO_THAP: 106,
    TAN_SO_CAO: 107,
    MAT_NGUON_PHA: 108,
    LECH_PHA: 109,
    NGUOC_PHA: 110,
    NGUONG_HAI_BAC_N: 111,
    NGUONG_TONG_HAI: 112,
    DONG_TRUNG_TINH: 113,
    DONG_TIEP_DIA: 114,
    CANH_BAO_1: 115,
    CANH_BAO_2: 116,
    LECH_AP_PHA: 117
}


const CONS = {
    LOCAL_HOST: HOST,
    DATE_FORMAT:"YYYY-MM-DD hh:mm:ss",
    METHOD_TYPE,
    ERROR,
    RESET_PASSWORD_TOKEN_LENGTH: 50,
    WARNING_TYPE
};

export default CONS;