const HOST = "http://localhost:9999/";
// const HOST = "http://192.168.1.45:9999/";

const METHOD_TYPE = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE",
    DOWNLOAD: "DOWNLOAD",
    DOWNLOAD_NEW: "DOWNLOAD_NEW"
}

const ERROR = {
    ACCOUNT_IS_LOCKED_BY_ADMIN: "ACCOUNT_IS_LOCKED_BY_ADMIN",
    ACCOUNT_IS_LOCKED: "ACCOUNT_IS_LOCKED",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    BAD_CREDITIAL: "BAD_CREDITIAL",
    BAD_REQUEST: "BAD_REQUEST",
    NOT_FOUND_EMAIL: "NOT_FOUND_EMAIL",
    EMAIL_IS_INVALID: "EMAIL_IS_INVALID",
    NEW_PASSWORD_SAME_CURRENT_PASSWORD: "NEW_PASSWORD_SAME_CURRENT_PASSWORD",
    CURRENT_PASSWORD_NOT_MATCH: "CURRENT_PASSWORD_NOT_MATCH",
    ERROR_UPDATE_PASSWORD: "ERROR_UPDATE_PASSWORD"
}

const WARNING_TYPE = {
    NGUONG_AP_CAO: 101,
    NGUONG_AP_THAP: 102,
    QUA_TAI: 103,
    HE_SO_CONG_SUAT_THAP: 104,
    TAN_SO_CAO: '105, 209',
    TAN_SO_THAP: '106, 210',
    LECH_PHA: 107,
    SONG_HAI: '108, 109, 110, 111',
    SONG_HAI_DIEN_AP_BAC_N: 109,
    SONG_HAI_DONG_DIEN_BAC_N: 108,
    NGUOC_PHA: 112,
    MAT_DIEN_TONG: 113,

    CHAM_DAT: 201, // 0: GROUND FAULT
    DIEN_AP_CAO_DC: 202, // 1: DC_OVER_VOLT
    MAT_KET_NOI_AC: 203, // 2: AC_DISCONNECT
    MAT_KET_NOI_DC: 204, // 3: DC_DISCONNECT
    MAT_NGUON_LUOI: 205, // 4: GRID_DISCONNECT
    DONG_MO_CUA: '206, 403', // 5: CABINET_OPEN
    NGAT_THU_CONG: 207, // 6: MANUAL_SHUTDOWN
    NHIET_DO_CAO: '208, 301', // 7: OVER_TEMP
    DIEN_AP_CAO_AC: 211, // 10: AC_OVER_VOLT
    DIEN_AP_THAP_AC: 212, // 11: AC_UNDER_VOLT
    HONG_CAU_CHI: 213, // 12: BLOWN_STRING_FUSE
    NHIET_DO_THAP: '214, 302', // 13: UNDER_TEMP
    MEMORY_LOSS: 215, // 14: MEMORY_LOSS
    HW_TEST_FAILURE: 216, // 15: HW_TEST_FAILURE

    DO_AM: '303, 304',

    FI_TU_RMU: 401,
    KHOANG_TON_THAT: 402,
    MUC_DAU_THAP: 404,
    ROLE_GAS: 405,
    CHAM_VO: 406,
    MUC_DAU_CAO: 407,
    CAM_BIEN_HONG_NGOAI: 408,
    AP_SUAT_NOI_BO_MBA: 409,
    ROLE_NHIET_DO_DAU: 410,
    NHIET_DO_CUON_DAY: 411,
    KHI_GAS_MBA: 412,

    PHONG_DIEN : '501, 601',

    AP_SUAT : '701, 702',

    LUU_LUONG : '1001, 1002'
}

const WARNING_TYPE_MST = {
    NGUONG_AP_CAO: 101,
    NGUONG_AP_THAP: 102,
    QUA_TAI: 103,
    HE_SO_CONG_SUAT_THAP: 104,
    TAN_SO_CAO_METER: 105,
    TAN_SO_THAP_METER: 106,
    LECH_PHA: 107,
    SONG_HAI_DONG_DIEN_BAC_N: 108,
    SONG_HAI_DIEN_AP_BAC_N: 109,
    TONG_MEO_SONG_HAI_DIEN_AP: 110,
    TONG_MEO_SONG_HAI_DONG_DIEN: 111,
    NGUOC_PHA: 112,
    MAT_DIEN_TONG: 113,

    CHAM_DAT: 201, // 0: GROUND FAULT
    DIEN_AP_CAO_DC: 202, // 1: DC_OVER_VOLT
    MAT_KET_NOI_AC: 203, // 2: AC_DISCONNECT
    MAT_KET_NOI_DC: 204, // 3: DC_DISCONNECT
    MAT_NGUON_LUOI: 205, // 4: GRID_DISCONNECT
    DONG_MO_CUA_INVERTER: 206, // 5: CABINET_OPEN
    NGAT_THU_CONG: 207, // 6: MANUAL_SHUTDOWN
    NHIET_DO_CAO_INVERTER: 208, // 7: OVER_TEMP
    TAN_SO_CAO_INVERTER: 209,
    TAN_SO_THAP_INVERTER: 210,
    DIEN_AP_CAO_AC: 211, // 10: AC_OVER_VOLT
    DIEN_AP_THAP_AC: 212, // 11: AC_UNDER_VOLT
    HONG_CAU_CHI: 213, // 12: BLOWN_STRING_FUSE
    NHIET_DO_THAP_INVERTER: 214, // 13: UNDER_TEMP
    MEMORY_LOSS: 215, // 14: MEMORY_LOSS
    HW_TEST_FAILURE: 216, // 15: HW_TEST_FAILURE

    NHIET_DO_CA0_TEMP: 301,
    NHIET_DO_THAP_TEMP: 302,
    DO_AM_CAO: 303,
    DO_AM_THAP: 304,

    FI_TU_RMU: 401,
    KHOANG_TON_THAT: 402,
    DONG_MO_CUA_STATUS: 403,
    MUC_DAU_THAP: 404,
    ROLE_GAS: 405,
    CHAM_VO: 406,
    MUC_DAU_CAO: 407,
    CAM_BIEN_HONG_NGOAI: 408,
    AP_SUAT_NOI_BO_MBA: 409,
    ROLE_NHIET_DO_DAU: 410,
    NHIET_DO_CUON_DAY: 411,
    KHI_GAS_MBA: 412,

    PHONG_DIEN_HTR02: 501,

    PHONG_DIEN_AMS01: 601,
}

const WARNING_TYPE_PV = {
    CHAM_DAT: 201, // 0: GROUND FAULT
    DIEN_AP_CAO_DC: 202, // 1: DC_OVER_VOLT
    MAT_KET_NOI_AC: 203, // 2: AC_DISCONNECT
    MAT_KET_NOI_DC: 204, // 3: DC_DISCONNECT
    MAT_NGUON_LUOI: 205, // 4: GRID_DISCONNECT
    DONG_MO_CUA: 206, // 5: CABINET_OPEN
    NGAT_THU_CONG: 207, // 6: MANUAL_SHUTDOWN
    NHIET_DO_CAO: 208, // 7: OVER_TEMP
    TAN_SO_CAO: 209, // 8: OVER_FREQUENCY
    TAN_SO_THAP: 210, // 9: UNDER_FREQUENCY
    DIEN_AP_CAO_AC: 211, // 10: AC_OVER_VOLT
    DIEN_AP_THAP_AC: 212, // 11: AC_UNDER_VOLT
    HONG_CAU_CHI: 213, // 12: BLOWN_STRING_FUSE
    NHIET_DO_THAP: 214, // 13: UNDER_TEMP
    MEMORY_LOSS: 215, // 14: MEMORY_LOSS
    HW_TEST_FAILURE: 216 // 15: HW_TEST_FAILURE

}

const WARNING_TYPE_GRID = {
    DO_AM: 501,
    PHONG_DIEN: 502,
    TAN_SO_THAP: 503,
    TAN_SO_CAO: 504,
    SONG_HAI: 505,
    QUA_TAI_TONG: 506,
    QUA_TAI_NHANH: 507,
    LECH_PHA_TONG: 508,
    LECH_PHA_NHANH: 509,
    FI_TU_RMU: 510,
    KHOANG_TON_THAT: 511,
    DONG_MO_CUA: 512,
    MUC_DAU_THAP: 513,
    NHIET_DO: 514,
    NHIET_DO_DAU: 515,
    MAT_DIEN_TONG: 516,
    MAT_DIEN_NHANH: 517,
    ROLE_GAS: 518,
    CHAM_VO: 519,
    MUC_DAU_CAO: 520,
    CAM_BIEN_HONG_NGOAI: 521,
    DIEN_AP_CAO: 522,
    DIEN_AP_THAP: 523,
    COS_TONG_THAP: 524,
    COS_NHANH_THAP: 525,
    AP_SUAT_NOI_BO_MBA: 526,
    ROLE_NHIET_DO_DAU: 527,
    NHIET_DO_CUON_DAY: 528,
    KHI_GAS_MBA: 529,
    HE_SO_CONG_SUAT_THAP: 530,
    SHADING: 531,
    HIEU_SUAT_THAP: 532,
    LOI_GATEWAY: 533

}

const CHART_TYPE_LOAD = {
    DONG_DIEN: 1,
    DIEN_AP: 2,
    CONG_SUAT_TAC_DUNG: 3,
    DIEN_NANG: 4,
    NHIET_DO_VI_TRI_1: 5,
    NHIET_DO_VI_TRI_2: 6,
    NHIET_DO_VI_TRI_3: 7,
    SONG_HAI_TUC_THOI: 8,
    SONG_HAI_THOI_DIEM: 9,
    SONG_HAI_KHOANG_THOI_GIAN: 10
}

const CHART_TYPE_PV = {
    DONG_DIEN: 1,
    DIEN_AP: 2,
    CONG_SUAT_TAC_DUNG: 3,
    DIEN_NANG: 4,
    NHIET_DO: 5,
    HIEU_SUAT: 6
}

const CHART_TYPE_GRID = {
    DONG_DIEN: 1,
    DIEN_AP: 2,
    CONG_SUAT_TAC_DUNG: 3,
    DIEN_NANG: 4,
    NHIET_DO_CUC: 5,
    NHIET_DO_KHOANG: 6,
    DO_AM: 7,
    LFB_RATIO: 8,
    LFB_EPPC: 9,
    MFB_RATIO: 10,
    MLFB_EPPC: 11,
    HLFB_RATIO: 12,
    HLFB_EPPC: 13,
    INDICATOR: 14
}

const ELECTRIC_POWER_NUMBER = {
    THOUSAND: 1000,
    MILLION: 1000000,
    BILLION: 1000000000
}

const VIEW_TYPE_ELECTRIC_POWER = {
    G: 1,
    M: 2,
    K: 3
}



const ROLES = {
    ROLE_ADMIN: "ROLE_ADMIN",
    ROLE_USER: "ROLE_USER",
    ROLE_MOD: "ROLE_MOD",
    ROLE_EVN: "ROLE_EVN"
}

const DEVICE_TYPE_LOAD = {
    METER: 1,
    CBNDDA: 3,
    CBTT: 4,
    HTR02: 5,
    AMS01: 6,
    CMAS: 7,
    RELAY: 8,
    GATEWAY: 9,
    CBLL: 10,
    CBBX: 11,
    CBMN: 12,
    CBPH: 13,
    CBTDG: 14,
    CBDLP: 15,
    STRING: 16
}

const OBJECT_TYPE_LOAD = {
    MBA: 1,
    TDHT: 2,
    DCD: 3,
    MB: 4,
    MNK: 5,
    DH: 6,
    QUAT: 7,
    CNC: 8,
    MT: 9,
    DEN: 10,
    PCB: 11,
    LN: 12,
    LS: 13,
    CHILLER: 14,
    AHU: 15,
    MH: 16,
    MC: 17,
    MDK: 18,
    MPD: 19,
    TTT: 20,
    INVERTER: 21,
    STRING: 22,
    DCb: 23,
    GATEWAY: 24
}


const DEVICE_TYPE_PV = {
    METER: 1,
    INVERTER: 2,
    CBNDDA: 3,
    CBTT: 4,
    HTR02: 5,
    AMS01: 6,
    CMAS: 7,
    RELAY: 8,
    GATEWAY: 9,
    CBLL: 10,
    CBBX: 11,
    CBMN: 12,
    CBPH: 13,
    CBTDG: 14,
    CBDLP: 15,
    STRING: 16
}

const DEVICE_TYPE_GRID = {
    METER: 1
}

const SYSTEM_TYPE = {
    LOAD: 1,
    PV: 2,
    WIND: 3,
    BATTERY: 4,
    GRID: 5
}

const LOAD_TYPE_METER = {
    SAN_XUAT: 1,
    VAN_PHONG: 2,
    CHIEU_SANG: 3,
    MAY_BOM: 4,
    LO_NUNG: 5,
    LO_HOI: 6,
    XU_LY_NUOC_THAI: 7,
    DIEU_HOA: 8,
    QUAT_GIO: 9,
    MAY_NEN: 10,
    KHAC: 11
}

const TAB_MENU = {
    OVERVIEW: 1,
    SYSTEM_MAP: 2,
    CHART: 3,
    WARNING: 4,
    DEVICE_INFORMATION: 5,
    REPORT: 6,
    SETTING_WARNING: 7,
    RECEIVER_WARNING: 8,
    SUPPORT: 9,
    DIAGNOSE: 10,
    MANUFACTURE: 11,
    SETTING_SHIFT: 12,
    PLAN: 13
}

const ANOTHER_MAP = {
    TONG_QUAN: 1,
    TRUYEN_THONG: 2,
    MAT_BANG: 3,
    DIEU_KHIEN: 4
}

const CONS = {
    LOCAL_HOST: HOST,
    TAB_MENU,
    DATE_FORMAT: "YYYY-MM-DD HH:mm:ss",
    DATE_FORMAT_OPERATE: "YYYY-MM-DD HH:mm",
    DATE_FORMAT_HEADER: "[Ngày] DD [Tháng] MM [năm] YYYY hh:mm:ss A",
    METHOD_TYPE,
    ERROR,
    DEVICE_TYPE_LOAD,
    OBJECT_TYPE_LOAD,
    DEVICE_TYPE_PV,
    DEVICE_TYPE_GRID,
    SYSTEM_TYPE,
    CHART_TYPE_LOAD,
    CHART_TYPE_PV,
    CHART_TYPE_GRID,
    LOAD_TYPE_METER,
    RESET_PASSWORD_TOKEN_LENGTH: 50,
    WARNING_TYPE,
    WARNING_TYPE_MST,
    WARNING_TYPE_PV,
    WARNING_TYPE_GRID,
    ELECTRIC_POWER_NUMBER,
    VIEW_TYPE_ELECTRIC_POWER,
    ROLES
};

export default CONS;